219: Feed Page
archiv333/archiv333-ios pull request #55
Opened 2022-07-13 05:39 UTC by MiteshiOS

## Task

- [219: Feed Page](https://trello.com/c/nsp3i2HL/219-feed-page)

## Description & Notes

- Added UI of "Sort By" in FeedViewController & SeeAllViewController
- Added UI of Grid View & List View in FeedViewController & SeeAllViewController
- Developed Single Product View (Added VariantCell)
- Completed Sort By Implementation in FeedViewController (Pending in SeeAllViewController due to API)

## Visuals

https://user-images.githubusercontent.com/17427703/178658529-a3cae62a-8f0f-4bbf-9e69-888578add4f8.mp4

2022-07-13 14:40 UTC, tejen requested changes
A few changes requested, and then you can re-request review.

2022-07-13 15:03 UTC, MiteshiOS commented on archiv333/Common/ArchivOptionPopUp/ArchivOptionListViewController.swift
> +        cell.selectionStyle = .none
Yes, that will also be fine. Actually, we are showing check mark already for the selected item, that's why I won't use style.

2022-07-13 16:31 UTC, MiteshiOS commented on archiv333/Common/ArchivOptionPopUp/ArchivOptionListViewController.swift
> +        cell.selectionStyle = .none
https://github.com/archiv333/archiv333-ios/pull/55/commits/e23cf9485a42de62dd61aa1ffb935f0f7ed75c4f

2022-07-13 16:32 UTC, MiteshiOS commented on archiv333/Views/Search Screen Cells/SeeAllViewController.swift
> +    }
@tejen https://github.com/archiv333/archiv333-ios/pull/55/commits/e23cf9485a42de62dd61aa1ffb935f0f7ed75c4f

2022-07-13 16:34 UTC, MiteshiOS commented on archiv333/Views/Search Screen Cells/SeeAllViewController.swift
> +        }else{
@tejen https://github.com/archiv333/archiv333-ios/pull/55/commits/b00fe933c51c256038ad1ab705f43750975ccbe7

2022-07-13 16:36 UTC, MiteshiOS commented on archiv333/View Controllers/Feed/FeedViewController.swift
> +        }else{
@tejen https://github.com/archiv333/archiv333-ios/pull/55/commits/bb160e484b14016ad94d0334b7e40d91c268fc55

2022-07-18 23:07 UTC, tejen approved these changes

2022-07-18 23:07 UTC, merged