150: Show discount amount on Checkout screen
archiv333/archiv333-ios pull request #80
Opened 2022-07-30 12:57 UTC by MiteshiOS

## Notes

- Added logical updates for showing the discount amount on the checkout screen

## Visuals

https://user-images.githubusercontent.com/17427703/181915333-63801e66-2b4e-4e7a-83dd-63b9bcb2288e.mp4

2022-08-01 18:53 UTC, tejen requested changes

2022-08-01 18:53 UTC, tejen commented on archiv333/View Controllers/Checkout/CheckoutViewController.swift
> +                DispatchQueue.main.async { self.present(viewControllerToPresent: alert) }
🔍 Does this need to be explicitly in the main thread? To present the alert here. @MiteshiOS

2022-08-02 06:20 UTC, MiteshiOS commented on archiv333/View Controllers/Checkout/CheckoutViewController.swift
> +                DispatchQueue.main.async { self.present(viewControllerToPresent: alert) }
@tejen Oho ya it's not needed. Let me correct it.

2022-08-03 15:12 UTC, tejen approved these changes

2022-08-03 15:12 UTC, merged

2022-08-03 15:24 UTC, tejen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Show discount amount on Checkout screen](https://trello.com/c/braR8TD6/150-show-discount-amount-on-checkout-screen)

2022-08-03 15:26 UTC, tejen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Show discount amount on Checkout screen](https://trello.com/c/braR8TD6/150-show-discount-amount-on-checkout-screen)