190: Enable deep-linking to product page when sharing on mobile
archiv333/archiv333-ios pull request #81
Opened 2022-08-03 11:09 UTC by MiteshiOS

## Notes

- Enabled Associated Domains and Added Domain Information in XCode=> Signing & Capabilities
- Added methods to receive events and information about the tapped link

## Visuals

Include any relevant GIFs or Screenshots here

https://user-images.githubusercontent.com/17427703/182593916-3fe92dd3-41f0-4b36-9995-667eb0436cb7.mp4

2022-08-03 15:20 UTC, tejen requested changes
@MiteshiOS some concerns for you to address

2022-08-03 15:20 UTC, tejen commented on archiv333/Common/SceneDelegate.swift
> +        print(url)
🧹 Print statements are not needed in production. Please remove. @MiteshiOS

2022-08-03 15:20 UTC, tejen commented on archiv333/Common/SceneDelegate.swift
> +                    ((UIApplication.shared.delegate as! AppDelegate).tabBarController!).push(viewControllerToPush: vc)
🐞 When the app is launched from a killed state, this will open the modal before the splash video plays. Please fix.

To experiment with this, comment out lines `96-98` in `TabBarController.swift` (screenshot below) in order to enable the splash video.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/1665102/182645569-07e52d08-fbb1-4717-93e2-56473df02520.png">

2022-08-04 08:42 UTC, MiteshiOS commented on archiv333/Common/SceneDelegate.swift
> +                    ((UIApplication.shared.delegate as! AppDelegate).tabBarController!).push(viewControllerToPush: vc)
Yes sure @tejen. The solution I am thinking of is to add some delay in function execution. Something like below, this way we can control our modal presentation as the video is 6 secs long. Please let me know your point of view on this one.
```
DispatchQueue.main.asyncAfter(deadline: .now() + 6.0) { [self] in
            handleUserActivity(userActivity: userActivity)
        }
```

2022-08-05 14:44 UTC, MiteshiOS commented on archiv333/Common/SceneDelegate.swift
> +                    ((UIApplication.shared.delegate as! AppDelegate).tabBarController!).push(viewControllerToPush: vc)
@tejen Added updates as per our discussion by handling user activity using Archiv.Session.initialUserActivity

2022-08-05 14:45 UTC, MiteshiOS commented on archiv333/Common/SceneDelegate.swift
> +        print(url)
@tejen Yes i removed it.

2022-08-05 16:25 UTC, tejen requested changes
🧹 Please review and resolve the build warnings caused by this PR. @MiteshiOS

2022-08-06 04:51 UTC, MiteshiOS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Enable deep-linking to product page when sharing on mobile ("Universal Links")](https://trello.com/c/aP4pvdlR/190-enable-deep-linking-to-product-page-when-sharing-on-mobile-universal-links)

2022-08-23 04:44 UTC, tejen approved these changes
🏆 Great work

2022-08-23 04:45 UTC, merged