156: Create reusable .nib to consolidate large black buttons across the app ("next", "save", "checkout")
archiv333/archiv333-ios pull request #82
Opened 2022-08-05 15:07 UTC by MiteshiOS

## Notes

- Added reusable nib for the large black button
- Implemented in product details for Add To Bag & Buy It Now

## Visuals
![Screenshot 2022-08-05 at 8 34 35 PM](https://user-images.githubusercontent.com/17427703/183105953-1ab91e13-f557-407a-b58d-e9e697262cd9.png)
![Screenshot 2022-08-05 at 8 36 15 PM](https://user-images.githubusercontent.com/17427703/183105977-98ea2af7-c7d4-4d32-9a3f-9d6aefd59290.png)

2022-08-06 04:46 UTC, MiteshiOS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create reusable .nib to consolidate large black buttons across the app ("next", "save", "checkout")](https://trello.com/c/GcLfSZSB/156-create-reusable-nib-to-consolidate-large-black-buttons-across-the-app-next-save-checkout)

2022-08-23 04:48 UTC, tejen requested changes

2022-08-23 04:48 UTC, tejen commented on archiv333/View Controllers/Home/ProductViewController.swift
> +    //@IBOutlet var ivAddToBagIcon: UIImageView!
🧹 Please cleanup all code in this PR, including this unused code. @MiteshiOS

2022-08-23 04:48 UTC, tejen commented on archiv333/View Controllers/Authentication/SignupEmailViewController.swift
> -        tfInput.text = tfInput.text?.trimmingCharacters(in: .whitespacesAndNewlines)
🧹 Please update nomenclature to discontinue inappropriate usage of `didTap` notation @MiteshiOS

2022-08-23 11:07 UTC, MiteshiOS commented on archiv333/View Controllers/Authentication/SignupEmailViewController.swift
> -        tfInput.text = tfInput.text?.trimmingCharacters(in: .whitespacesAndNewlines)
Done @tejen

2022-08-29 18:18 UTC, tejen approved these changes

2022-08-30 03:56 UTC, merged