87: Push notifications
archiv333/archiv333-ios pull request #85
Opened 2022-08-30 14:17 UTC by MiteshiOS

## Notes

- Added setup and methods related to push notification

## Visuals
![IMG_9395](https://user-images.githubusercontent.com/17427703/187460979-d0fc24f6-55a2-4b68-9b62-155104f9384d.PNG)
![IMG_9396](https://user-images.githubusercontent.com/17427703/187461015-e08dd229-aeb5-460a-a147-16550fc3f60b.PNG)

2022-08-30 14:18 UTC, MiteshiOS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Push notifications](https://trello.com/c/A7r5HdsE/87-push-notifications)

2022-08-31 18:17 UTC, tejen requested changes
🐞 One requested change to make in the meantime, while I prepare to add more commits for networking.

2022-08-31 18:17 UTC, tejen commented on archiv333/View Controllers/Checkout/ProcessingPaymentViewController.swift
>              let vc = Utils.instantiateVC(identifier: "BottomMessageViewController") as! BottomMessageViewController
🐞 Should the `askForEnableNotifications()` call be within `DispatchQueue.main.async { ... }`, since it presents an alert view controller? @MiteshiOS

2022-09-01 12:21 UTC, MiteshiOS commented on archiv333/View Controllers/Checkout/ProcessingPaymentViewController.swift
>              let vc = Utils.instantiateVC(identifier: "BottomMessageViewController") as! BottomMessageViewController
Please check line no 73, the function itself is already getting called in `DispatchQueue.main.async { ... }`
Also, I tested it and it shows me alert for the go-to setting and enables notification. You can check 2nd screenshot. Let me know if you still need to add in the main queue.

2022-09-06 11:36 UTC, tejen commented on archiv333/View Controllers/Checkout/ProcessingPaymentViewController.swift
>              let vc = Utils.instantiateVC(identifier: "BottomMessageViewController") as! BottomMessageViewController
Okay. In that case, sounds like line 163 is unneeded? Since the entire method is getting called in `DispatchQueue.main.async { ... }` @MiteshiOS

2022-09-07 04:45 UTC, MiteshiOS commented on archiv333/View Controllers/Checkout/ProcessingPaymentViewController.swift
>              let vc = Utils.instantiateVC(identifier: "BottomMessageViewController") as! BottomMessageViewController
Yes, correct but need to check that code part after line no 163. Actually `askForEnableNotifications()` this method is also doing UI updates and when I tested there is no warning from the compiler. The code after 163 was already there I just added my function to present a notification alert. I request you to please test it from your end once because I was not able to place an order from my end in dev env. Please let me know if any.

2022-09-21 18:00 UTC, tejen commented on archiv333/View Controllers/Checkout/ProcessingPaymentViewController.swift
>              let vc = Utils.instantiateVC(identifier: "BottomMessageViewController") as! BottomMessageViewController
I've made the changes for you, so you can see what I mean about the thread issue. [Commit 8c1fe3f](https://github.com/archiv333/archiv333-ios/pull/85/commits/8c1fe3f360c03eafede86e486932929ef562e712) shows the changes @MiteshiOS

2022-09-21 18:02 UTC, tejen commented on archiv333/View Controllers/Checkout/ProcessingPaymentViewController.swift
>              let vc = Utils.instantiateVC(identifier: "BottomMessageViewController") as! BottomMessageViewController
🐞 We also have another critical bug here, the technique for checking whether user has Allowed Notifications or not (`let isRegisteredForRemoteNotifications = UIApplication.shared.isRegisteredForRemoteNotifications`) no longer works, as of iOS 10. See [Commit 93789fa](https://github.com/archiv333/archiv333-ios/pull/85/commits/93789fa8d2ed002d3de339b10029c13e9a0db1fa) to see my fix for this.

2022-09-21 18:12 UTC, merged