290: Shipping Cost (Checkout)
archiv333/archiv333-ios pull request #95
Opened 2022-11-12 05:52 UTC by MiteshiOS

## Notes

- Removed shipping from “delivery” cell and include as new cell under “subtotal” and above “payment processing fee”

## Visuals
![Simulator Screen Shot - iPhone 14 - 2022-11-12 at 11 20 50](https://user-images.githubusercontent.com/17427703/201459521-14f33cac-6732-4079-8808-4523461d3f77.png)

2022-11-12 05:52 UTC, MiteshiOS commented
![](https://github.trello.services/images/mini-trello-icon.png) [shipping cost (checkout)](https://trello.com/c/lzi1K0jm/290-shipping-cost-checkout)

2022-11-13 02:22 UTC, tejen requested changes
🐞 Some bugs to address @MiteshiOS

2022-11-13 02:22 UTC, tejen commented on archiv333/Common/Archiv.swift
> -        return (Archiv.Session.cart.reduce(shippingFee(destination: destination)) {
🐞 Bug: if we are removing `shippingFee` from `subtotal`, then check for all usages of `subtotal`. It looks like `subtotal` is being used in the `fee` method (to calculate Payment Processing Fee, which should be 2.9% + $0.30 of the total). The `fee` method needs to take into account the `shippingFee` in order to calculate Payment Processing Fee accurately.

2022-11-13 02:22 UTC, tejen commented on archiv333/Common/Archiv.swift
> +        return (Archiv.Session.cart.reduce(0) {
🔍 Should the initial value be `0.0` (float) rather than `0` (int), in order to preserve decimal precision for every iteration of the reduce function?

2022-11-13 02:22 UTC, tejen commented on archiv333/Common/Archiv.swift
> +        } + Archiv.Session.totalAdjustment )
🧹 Extraneous space at the end of this line

2022-11-13 02:22 UTC, tejen commented on archiv333/View Controllers/Checkout/CheckoutViewController.swift
> +        "CheckoutTotalCell",
👍 Good re-use of `CheckoutTotalCell`

2022-11-13 02:22 UTC, tejen commented on archiv333/View Controllers/Checkout/CheckoutViewController.swift
>              (cell as! CheckoutTotalCell).lbTotal.text = "$" + (Archiv.Session.cart.fees(destination: selectedDestination)).roundedToTwoDecimals()
🐞 As mentioned in another comment on this PR review, the `fees` no longer takes into account `shippingFee`, rendering the `fee` inaccurate.

2022-11-30 05:30 UTC, MiteshiOS commented on archiv333/Common/Archiv.swift
> -        return (Archiv.Session.cart.reduce(shippingFee(destination: destination)) {
Done. Please check it.

```
Old Formula
(cell as! CheckoutTotalCell).lbTotal.text = "$" + (Archiv.Session.cart.subtotal(destination: selectedDestination) * 1.029 + 0.3 + Archiv.Session.cart.shippingFee(destination: selectedDestination)).roundedToTwoDecimals()

New Formula
  // Grand Total with Subtotal + Shipping Fee + Payment Processing Fee            
(cell as! CheckoutTotalCell).lbTotal.text = "$" + (Archiv.Session.cart.subtotal(destination: selectedDestination) + Archiv.Session.cart.shippingFee(destination: selectedDestination) + Archiv.Session.cart.fees(destination: selectedDestination)).roundedToTwoDecimals()
```

2022-11-30 19:51 UTC, tejen approved these changes

2022-12-01 05:01 UTC, merged